### ISSUE TITLE
User Story #12: As a Seller, I want to post product ads because it will allow me to sell products online.

### ISSUE THREAD

**Issue by spaceGB** [PranavaaKirupakaran/SOEN341_Project#65]
Related Tasks:
- #66 
- #67 
- #68

**Comment by PranavaaKirupakaran** [comment]
User Story #12 (Issue #65)
Acceptance Test:
Successful Test: 
 - Log in as seller
 - Hover over my account and click on my products
 - Click on Add new product
 - Add/Amend all the required informations on the form
 - Publish the product 
 - Message get printed:"Item get added to the inventory"


 Unsuccesful Test:

 - Log in as seller
 - Hover over my account and click on my products
 - Click on Add new product
 - Add/Amend some informations on the form but left out some
 - Publish the product
 - Item does not get added since form is not fully completed.
